{"name": "Тест логин с неверным логином и паролем", "status": "passed", "description": "Проверяем, что запрос на логин вернул статус 401 и в тело запроса содержит фразу: \"success\": False, \"message\": \"email or password are incorrect\"", "steps": [{"name": "Логин пользователя через post запрос", "status": "passed", "start": 1744040743482, "stop": 1744040743588}], "start": 1744040743482, "stop": 1744040743588, "uuid": "fc4f0dfa-644f-4456-9a6f-4bc862a0c9fe", "historyId": "16a5118681c5978d077c756b9b325eb7", "testCaseId": "16a5118681c5978d077c756b9b325eb7", "fullName": "tests.tests_client_logining.TestClientLogining#test_registered_client_twice_return_403_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "tests_client_logining"}, {"name": "subSuite", "value": "TestClientLogining"}, {"name": "host", "value": "Wizzard_note"}, {"name": "thread", "value": "12384-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_client_logining"}]}