{"name": "Тест на создание пользователя, который уже существует", "status": "passed", "description": "Проверяем, что запрос на регистрацию вернул статус 403 и в тело запроса содержит фразу: \"success\": False, \"message\": \"User already exists\"", "steps": [{"name": "Создание пользователя через post запрос.", "status": "passed", "start": 1744040763804, "stop": 1744040764390}], "start": 1744040763804, "stop": 1744040764391, "uuid": "3e6f998a-431e-42d0-bf5e-85d31a367c78", "historyId": "0faf7bd9c4e18a4114b63962c95b0b65", "testCaseId": "0faf7bd9c4e18a4114b63962c95b0b65", "fullName": "tests.tests_client_registering.TestClientRegistering#test_registered_client_twice_return_403_success", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "tests_client_registering"}, {"name": "subSuite", "value": "TestClientRegistering"}, {"name": "host", "value": "Wizzard_note"}, {"name": "thread", "value": "13564-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_client_registering"}]}